### ISSUE TITLE
Simplify Function

### ISSUE THREAD

**Issue by Coalpha** [Coalpha/waluigi-ti.me#2]
After activating Keven and simplifying with Keven active. Once you deactivate Keven. Simplify adds instead of subtracting.

**Comment by legodude17** [comment]
That is because the first simplify adds `"k"` to `baseId`, it sets keven to -2 then it will simplify with `"k"` in `baseId`.

**Comment by legodude17** [comment]
My PR #3 will fix that.

**Comment by Coalpha** [comment]
Alright the pull request worked (I think)
